### ISSUE TITLE
Error when executing code.

### ISSUE THREAD

**Issue by Nickles255** [lzhengem/Java111b_Assignment5_Temperature#3]
Testing the ReadInPut method throw exception. below.
   Exception in thread "main" java.util.InputMismatchException
           at java.util.Scanner.throwFor(Unknown Source)
           at java.util.Scanner.next(Unknown Source)
           at java.util.Scanner.nextShort(Unknown Source)
           at java.util.Scanner.nextShort(Unknown Source)
           at Temperature.ReadInPut(Temperature.java:38)
           at Temperature_Tester.main(Temperature_Tester.java:9)

**Comment by kryptonianS** [comment]
I renamed the ReadInput to readInput.
I added in: char type[]=input.next().toCharArray(); to convert the input to a char type.
